# Generated by Django 5.1.4 on 2025-02-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_signup",
            name="email_otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
